### ISSUE TITLE
请问如何用Qwen-14B进行重新训练

### ISSUE THREAD

**Issue by delltower** [Coobiw/MiniGPT4Qwen#11]

**Comment by Coobiw** [comment]
显存够用的话，直接修改config文件里的`llm_model`项，改成14B的checkpoint路径就可以，我最近也会放一个在2张3090用流水线并行训练的14B版本

**Comment by Coobiw** [comment]
已更新双卡流水线并行训练Qwen-14B-Chat的版本：[commit](https://github.com/Coobiw/MiniGPT4Qwen/commit/1fa02d014d0ee9e34db195080e8b2e38eaf6e671)

**Comment by Coobiw** [comment]
Qwen-14B pipeline parallel training is supported. I'll close this issue
