### ISSUE TITLE
请问如何减少训练时长

### ISSUE THREAD

**Issue by xiyuanhao** [Coobiw/MiniGPT4Qwen#14]
预训练loss 到1.4左右，step到900多 就基本不动了，然后还一直训练？是我的显卡问题么？

**Comment by Coobiw** [comment]
是在哪个setting跑的呢，然后loss趋于平缓也很正常，并不是说loss基本不动就会停止啊

**Comment by Coobiw** [comment]
I've pushed the loss curves in README. I'll close this issue.
