### ISSUE TITLE
请问是否支持 流水线并行 推理

### ISSUE THREAD

**Issue by valencebond** [Coobiw/MiniGPT4Qwen#15]
从而减少 bubble time

**Comment by Coobiw** [comment]
推理上应该不太存在bubble time的问题，这个主要是训练上的

现在推理没支持PP，但是支持了mapping到multi-gpu上（采用了transformers的`device_map="auto"`的方法实现）

可以参考刚才的commit：[https://github.com/Coobiw/MiniGPT4Qwen/commit/683326bcba26ca6dfd516f5ef48f2c35e71b2c0d](https://github.com/Coobiw/MiniGPT4Qwen/commit/683326bcba26ca6dfd516f5ef48f2c35e71b2c0d)

**Comment by Coobiw** [comment]
It's been a long time. I'll close this issue.
