### ISSUE TITLE
请问Qwen-7B的权重文件是只需要LFS的吗？还是全部文件都要呢？

### ISSUE THREAD

**Issue by cszhengyh** [Coobiw/MiniGPT4Qwen#16]

**Comment by Coobiw** [comment]
全部文件，如果你的机器可以正常访问huggingface，可以使用
```python
# Load model directly
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", trust_remote_code=True,cache_dir=your_path)
```
会自动下载到你指定的`cache_dir`中

参考：
<img width="1442" alt="image" src="https://github.com/Coobiw/MiniGPT4Qwen/assets/48615375/dc2fc869-0709-4d54-9c1a-28f057ee3d40">

**Comment by Coobiw** [comment]
Has been solved
