### ISSUE TITLE
关于知乎中提到的多模态接入方案问题

### ISSUE THREAD

**Issue by cszhengyh** [Coobiw/MiniGPT4Qwen#17]
我理解是在推理时用到特有的接入方案，但是我在项目演示截图，在我们的指令中并没有看到类似`<Img><ImageHere></Img>`的输入嵌入？这是为什么呢？

**Comment by cszhengyh** [comment]
我看我们的训练数据中，都是将`<Img><ImageHere></Img>`放在最前面的，所以我猜测我们训练时没有用到这个方案

**Comment by cszhengyh** [comment]
我搞错了  那个好像是多图才会用到...

**Comment by Coobiw** [comment]
无论训练还是推理都是有用到`<Img><ImageHere></Img>`的

推理的在`cli_demo`和`webui_demo`两个py文件里，直接在文本端做处理，加上image相关的文本以及构成对话模板，都有相应的代码，可以check一下

训练则是`preprocess` func会把`<ImageHere>`替换成`num_queries`个qformer处理后的image token。

详情可以看这些代码部分：
- [训练时对token的preprocess](https://github.com/Coobiw/MiniGPT4Qwen/blob/master/lavis/models/minigpt4qwen_models/minigpt4qwen.py#L226)
- [推理时的加入image文本-cli_demo](https://github.com/Coobiw/MiniGPT4Qwen/blob/master/cli_demo.py#L236)
- [推理时的加入image文本-webui_demo](https://github.com/Coobiw/MiniGPT4Qwen/blob/master/webui_demo.py#L129)
<img width="781" alt="image" src="https://github.com/Coobiw/MiniGPT4Qwen/assets/48615375/9f04bfeb-9632-4965-944e-86962bbece5c">

Additionally，这个和多图没关系，有图像输入就需要

**Comment by cszhengyh** [comment]
> 无论训练还是推理都是有用到`<Img><ImageHere></Img>`的
> 
> 推理的在`cli_demo`和`webui_demo`两个py文件里，直接在文本端做处理，加上image相关的文本以及构成对话模板，都有相应的代码，可以check一下
> 
> 训练则是`preprocess` func会把`<ImageHere>`替换成`num_queries`个qformer处理后的image token。
> 
> 详情可以看这些代码部分：
> 
> * [训练时对token的preprocess](https://github.com/Coobiw/MiniGPT4Qwen/blob/master/lavis/models/minigpt4qwen_models/minigpt4qwen.py#L226)
> * [推理时的加入image文本-cli_demo](https://github.com/Coobiw/MiniGPT4Qwen/blob/master/cli_demo.py#L236)
> * [推理时的加入image文本-webui_demo](https://github.com/Coobiw/MiniGPT4Qwen/blob/master/webui_demo.py#L129)
> 
> <img alt="image" width="781" src="https://private-user-images.githubusercontent.com/48615375/326392092-9f04bfeb-9632-4965-944e-86962bbece5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODQxODQsIm5iZiI6MTcxNDM4Mzg4NCwicGF0aCI6Ii80ODYxNTM3NS8zMjYzOTIwOTItOWYwNGJmZWItOTYzMi00OTY1LTk0NGUtODY5NjJiYmVjZTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA5NDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZmE4NTMwOWVkNGEyOTA5ZjkwMTZkZWNmZDA4Y2M5Y2E2YjZlZjcyNjQ1N2U4NzM2NTg0NTM4MThjYTk2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ax21wpP3eEqeftpoWSipq9SwBmoAbgf7GKDy9iYJ0g">
> Additionally，这个和多图没关系，有图像输入就需要

我理解这种接入方案，`<Img><ImageHere></Img>`应该不局限于置于文本最前方，而是还会插在中间，这在训练数据中没有体现这样的数据。在推理的时候，我们用的也是绝对前缀？

**Comment by Coobiw** [comment]
嗯 实现上是完全不局限的 现在代码实现为了方便都放在最前面 你可以去修改代码 插入在任意位置都是可以的

**Comment by Coobiw** [comment]
solved. I'll close this issue.
