### ISSUE TITLE
是否支持QWEN-14B的INT4的量化版本？

### ISSUE THREAD

**Issue by yumianhuli2** [Coobiw/MiniGPT4Qwen#18]
是否支持QWEN-14B的INT4的量化版本？谢谢！

**Comment by Coobiw** [comment]
可以比较容易的支持进去 你可以更改config文件中的`llm_model`[https://github.com/Coobiw/MiniGPT4Qwen/blob/master/lavis/configs/models/minigpt4qwen/minigpt4qwen-14b.yaml#L34](https://github.com/Coobiw/MiniGPT4Qwen/blob/master/lavis/configs/models/minigpt4qwen/minigpt4qwen-14b.yaml#L34)

然后可以下载Qwen-14B-Int4的权重，把绝对路径写到这里就行了

如果训练的话 可以在lavis/projects/[your_dir]/[your_config].yaml里加上`llm_model`,指定你的int4模型路径即可

**Comment by yumianhuli2** [comment]
> 可以比较容易的支持进去 你可以更改config文件中的`llm_model`https://github.com/Coobiw/MiniGPT4Qwen/blob/master/lavis/configs/models/minigpt4qwen/minigpt4qwen-14b.yaml#L34
> 
> 然后可以下载Qwen-14B-Int4的权重，把绝对路径写到这里就行了
> 
> 如果训练的话 可以在lavis/projects/[your_dir]/[your_config].yaml里加上`llm_model`,指定你的int4模型路径即可

好的，3Q

**Comment by Coobiw** [comment]
solved. I'll close this issue.
