### ISSUE TITLE
Code confusion

### ISSUE THREAD

**Issue by abbhay** [Coobiw/MiniGPT4Qwen#2]
https://github.com/Coobiw/MiniGPT4Qwen/blob/d13f9657614a6be7553c850b7f95b4c31832eeef/lavis/models/minigpt4qwen_models/minigpt4qwen.py#L110C18-L110C18
predefine ：qformer_text_input = True 
lavis repo code ：self.Qformer.resize_token_embeddings(len(self.tokenizer))

your code：raise NotImplementedError

Why do you change it like this?

**Comment by Coobiw** [comment]
BLIP2 not support text input for Q-former. But InstuctBLIP support it. In this project, I use blip2 qformer not instructblip one. If you use instructblip q-former, you can change this code into the lavis one.
