### ISSUE TITLE
AI 无法理解图片

### ISSUE THREAD

**Issue by liuling19941216** [Coobiw/MiniGPT4Qwen#24]
第一步骤：上传图片-提问
报错图片
![Uploading 页面报错.png…]()

2、查看后台，图片显示
![Uploading cmd.png…]()

**Comment by Coobiw** [comment]
你好，你的图片没有上传上来

**Comment by liuling19941216** [comment]
![cmd](https://github.com/Coobiw/MiniGPT4Qwen/assets/173139714/c723d2b0-6a48-432b-b5be-e06991f630d7)
![Uploading 页面报错.png…]()

**Comment by liuling19941216** [comment]
![Uploading 页面报错.png…]()

**Comment by liuling19941216** [comment]
![Uploading 效果图2.png…]()

**Comment by Coobiw** [comment]
我有两个问题需要确认下：
1. 你的运行命令是
```
python webui _demo. py --model-type qwen7b_chat -c lavis/output/pp_7b_video/sft_video/global_step2005/unfreeze_llm_model.pth --llm_device_map auto"
```
这个checkpoint:`lavis/output/pp_7b_video/sft_video/global_step2005/unfreeze_llm_model.pth`用的是什么，我来没来得及上传这个checkpoint，你说下载了其他checkpoint用上了吗

2.你上传的图像是什么，我可以在我这里给你试一下，看看跑出来什么样子

**Comment by Coobiw** [comment]
图片几乎都fail掉了...上传的时候可以等待一下，看到出现图片再提交

**Comment by liuling19941216** [comment]
1、我用的是你写的执行命令生成的 ，不是这样生成的吗
sft阶段
（需要转换projection层和所有LLM的参数）

python pipemodel2pth.py --ckpt-dir lavis/output/pp_7b_video/sft_video/global_step2005
转换后，模型文件会存储在ckpt_dir底下，名为unfreeze_llm_model.pth
2、图片用的就是你MiniGPT4Qwen-master\examples\minigpt4_image_3.jpg 这张图

**Comment by liuling19941216** [comment]
![页面报错](https://github.com/Coobiw/MiniGPT4Qwen/assets/173139714/ea90df12-b4f0-42eb-a4f5-3660ae830f0b)
![minigpt4+通义千问的效果图](https://github.com/Coobiw/MiniGPT4Qwen/assets/173139714/e0140a6e-ba54-47f5-9439-33a197b8d5b1)

**Comment by Coobiw** [comment]
请问你是自己训练了之后进行的权重转换吗？这个脚本是训练之后将deepspeed pipeline parallel权重转换成pth的脚本，如果没训练直接调用是不对的。

这是我刚才测试的case：
<img width="1347" alt="image" src="https://github.com/Coobiw/MiniGPT4Qwen/assets/48615375/efc64096-49f9-4063-a713-f858a5425eef">
<img width="1319" alt="image" src="https://github.com/Coobiw/MiniGPT4Qwen/assets/48615375/ad8d69fd-cb65-4afd-9a9f-684a6a643e74">

**Comment by Coobiw** [comment]
Solved in WeChat. I'll close this issue.
