### ISSUE TITLE
继续在新的数据集上进行SFT报错

### ISSUE THREAD

**Issue by AhLok-Chow** [Coobiw/MiniGPT4Qwen#35]
如何在新的数据集上继续SFT？已经修改了lavis/configs/llava_xray/default.yaml，但读取图片的时候会报错
下面是我的报错：
Traceback (most recent call last):
  File "/work/zilezhou/code/MPP-LLaVA/train_pipeline.py", line 261, in <module>
    main()
  File "/work/zilezhou/code/MPP-LLaVA/train_pipeline.py", line 232, in main
    loss = engine.train_batch(data_iter=train_iter)
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/deepspeed/runtime/pipe/engine.py", line 373, in train_batch
    self._exec_schedule(sched)
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/deepspeed/runtime/pipe/engine.py", line 1373, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/deepspeed/runtime/pipe/engine.py", line 814, in _exec_load_micro_batch
    batch = self._next_batch()
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/deepspeed/runtime/pipe/engine.py", line 645, in _next_batch
    batch = next(self.data_iterator)
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/deepspeed/runtime/dataloader.py", line 34, in __next__
    batch = next(self.data_iter)
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 243, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/work/zilezhou/code/MPP-LLaVA/lavis/datasets/datasets/minigpt4_instructions.py", line 41, in __getitem__
    image = Image.open(image_path).convert("RGB")
  File "/home/zilezhou/anaconda3/envs/minigpt4qwen/lib/python3.9/site-packages/PIL/Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/work/zilezhou/code/MPP-LLaVA/cache/dataset/xray/3677_1.png'

**Comment by Coobiw** [comment]
你这个是路径错误 可以看下你的目录结构、dataset的config文件和训练时用的config文件吗

**Comment by AhLok-Chow** [comment]
> 你这个是路径错误 可以看下你的目录结构、dataset的config文件和训练时用的config文件吗

目录结构：
├── cache
│   └── dataset
│       ├── llava_xray
│   │   │   ├── xray_images
│   │   │   ├── llava_instruction_xray_open_zh.json


dataset的config文件：

datasets:
  llava_xray:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /export/dataset/llava_xray/llava_instruction_xray_open_zh.json
          storage: dataset/llava_xray/llava_instruction_xray_open_zh.json
      images:
          storage: dataset/llava_xray/xray_images

训练的config

model:
  arch: minigpt4qwen
  model_type: qwen7b_chat
  load_finetuned: True
  load_pretrained: True

  # pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/blip2_pretrained_flant5xxl.pth"
  pretrained: "ckpt/blip2/blip2_pretrained_flant5xxl.pth"
  finetuned: "/work/zilezhou/code/MPP-LLaVA/lavis/output/pp_7b/sft/global_step4893/model.pth"

  # vit encoder
  vit_model: "eva_clip_g"
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: True
  vit_precision: "fp16"  # 如果你要打开vit进行训练，这里需要调整成fp32,否则如果开启amp混合精度训练会有问题（在scaler处报错,因为没有实现一个fp16的AdamW）
  freeze_vit: True
  unfreeze_pos_embed: False

  # Q-Former
  num_query_token: 32
  qformer_text_input: False
  freeze_qformer: True
  freeze_queries: True

  # projection
  freeze_proj: False

  # path to Vicuna checkpoint
  llm_model: "ckpt/Qwen7B-chat"

  # unfreeze LLM for better chat
  freeze_llm: False

  # lora config
  get_lora: False
  lora_alpha: 32
  lora_r: 8
  lora_dropout: 0.05

  # text length when training
  max_txt_len: 512 # 512 #1536

  # enable autocast of vit
  enable_autocast: False

datasets:
  llava_xray: # name of the dataset builder
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
    text_processor:
        train:
          name: "base_instruction"
          max_words: 200

run:
  output_dir: "lavis/output/pp_7b/sft_xray/"

  task: deepspeed_image_text_pretrain

  num_workers: 4

  seed: 42

  world_size: 1
  dist_url: "env://"
  distributed: True

  max_epoch: 1
  log_freq: 10

  lr_sched: "linear_warmup_cosine_lr_step-wise"
  warmup_lr: 0
  init_lr: 2e-5
  min_lr: 0
  warmup_ratio: 0.1

  deepspeed_config:
    # global batch = 128 = n_ranks * grad_acc_steps * micro_batch_size = (4//2) * 64 * 1
    # 8 x 3090
    # pp=2 dp=4 nproc=pp*dp=8 
    # pp=8 dp=1 nproc=pp*dp=8 (before)
    # grad_acc_steps 越大，batch越小，速度越慢，但是显存占用越小
    # micro_batch_size_per_gpu 越大，batch越大，速度越快，但是显存占用越大
    gradient_accumulation_steps: 32 # 128 // dp(=4) // bs_per_gpu(=1) = 128 # 32 先跑了32,128还没试
    train_micro_batch_size_per_gpu: 1

    gradient_clipping: 1.
    steps_per_print: 10
    wall_clock_breakdown: false
    dump_state: False

    fp16:
        enabled: false
        loss_scale: 0
        loss_scale_window: 1000
        initial_scale_power: 16
        hysteresis: 2
        min_loss_scale: 1

    bf16:
        enabled: true

    optimizer:
        type: "AdamW"
        params:
            lr: 2e-5
            betas: [0.9,0.99]
            eps: 1e-7
            weight_decay: 0.

    zero_optimization:
        stage: 0
        # offload_optimizer:
        #   device: "cpu"
        #   pin_memory: true
        allgather_partitions: true
        allgather_bucket_size: 2e8
        overlap_comm: true
        reduce_scatter: true
        reduce_bucket_size: 2e8
        contiguous_gradients: true

**Comment by AhLok-Chow** [comment]
# 目录结构：
├── cache
│   └── dataset
│       ├── llava_xray
│   │   │   ├── xray_images
│   │   │   |   ├── ...
│   │   │   ├── llava_instruction_xray_open_zh.json

# dataset config:

datasets:
  llava_xray:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /export/dataset/llava_xray/llava_instruction_xray_open_zh.json
          storage: dataset/llava_xray/llava_instruction_xray_open_zh.json
      images:
          storage: dataset/llava_xray/xray_images

# 训练config：
model:
  arch: minigpt4qwen
  model_type: qwen7b_chat
  load_finetuned: True
  load_pretrained: True


  pretrained: "ckpt/blip2/blip2_pretrained_flant5xxl.pth"
  finetuned: "/work/zilezhou/code/MPP-LLaVA/lavis/output/pp_7b/sft/global_step4893/model.pth"

  vit_model: "eva_clip_g"
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: True
  vit_precision: "fp16"  
  freeze_vit: True
  unfreeze_pos_embed: False


  num_query_token: 32
  qformer_text_input: False
  freeze_qformer: True
  freeze_queries: True

  freeze_proj: False

  llm_model: "ckpt/Qwen7B-chat"


  freeze_llm: False


  get_lora: False
  lora_alpha: 32
  lora_r: 8
  lora_dropout: 0.05

 
  max_txt_len: 512 # 512 #1536


  enable_autocast: False

datasets:
  llava_xray: # name of the dataset builder
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
    text_processor:
        train:
          name: "base_instruction"
          max_words: 200

run:
  output_dir: "lavis/output/pp_7b/sft_xray/"

  task: deepspeed_image_text_pretrain

  num_workers: 4

  seed: 42

  world_size: 1
  dist_url: "env://"
  distributed: True

  max_epoch: 1
  log_freq: 10

  lr_sched: "linear_warmup_cosine_lr_step-wise"
  warmup_lr: 0
  init_lr: 2e-5
  min_lr: 0
  warmup_ratio: 0.1

  deepspeed_config:
    gradient_accumulation_steps: 32 # 128 // dp(=4) // bs_per_gpu(=1) = 128 # 32 先跑了32,128还没试
    train_micro_batch_size_per_gpu: 1

    gradient_clipping: 1.
    steps_per_print: 10
    wall_clock_breakdown: false
    dump_state: False

    fp16:
        enabled: false
        loss_scale: 0
        loss_scale_window: 1000
        initial_scale_power: 16
        hysteresis: 2
        min_loss_scale: 1

    bf16:
        enabled: true

    optimizer:
        type: "AdamW"
        params:
            lr: 2e-5
            betas: [0.9,0.99]
            eps: 1e-7
            weight_decay: 0.

    zero_optimization:
        stage: 0


        allgather_partitions: true
        allgather_bucket_size: 2e8
        overlap_comm: true
        reduce_scatter: true
        reduce_bucket_size: 2e8
        contiguous_gradients: true

**Comment by Coobiw** [comment]
按照这个里面修改目录结构：[DATA.md](https://github.com/Coobiw/MPP-LLaVA/blob/master/DATA.md)

然后注意下你的dataset里的anno（llava_instruction_xray_open_zh.json）里的图片路径需要是相对vis_root的（dataset/llava_xray/xray_images），**或者可以全部路径都直接使用绝对路径**

**Comment by AhLok-Chow** [comment]
昨晚昏头忘记改anno路径了，感谢。
