### ISSUE TITLE
pip install -e .报错

### ISSUE THREAD

**Issue by MichaelWowTJ** [Coobiw/MiniGPT4Qwen#37]
<img width="1250" alt="03bb54458a40ed6a94690de218c7aa0" src="https://github.com/user-attachments/assets/53fcf510-6717-4416-b09e-d883c1c6a548">
<img width="1274" alt="c214e78b65d3a8ee8954660b7104071" src="https://github.com/user-attachments/assets/5a9a5a23-cb63-4c9f-b2f8-bb91dc3c2c40">
这是什么原因啊？救救孩子。

**Comment by Coobiw** [comment]
python版本看起来有问题。。。

**Comment by MichaelWowTJ** [comment]
> python版本看起来有问题。。。

我安装的也是3.8

**Comment by Coobiw** [comment]
按requirements.txt里逐个pip install，看一下是哪个package有问题

**Comment by MichaelWowTJ** [comment]
已找到原因，spacy默认安装3.8，将spacy降成3.7即可。感谢博主。

**Comment by JaredandLee** [comment]
只需要在requirements.txt文件中的spacy后面加上==3.7即可

**Comment by Coobiw** [comment]
已经加入requirements.txt 感谢
